version: '3.8'

services:
  backend:
    build: ./server
    depends_on:
      - ollama
    env_file:
      - .env
    ports:
      - 5001:5001
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    command: npm run start
    extra_hosts:
    - "host.docker.internal:host-gateway"
  frontend:
    build: ./client
    env_file:
      - ./client/.env.local
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/mochawesome-report
    command: npm run dev
    extra_hosts:
    - "host.docker.internal:host-gateway"
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    command: serve